apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
  labels:
    app: sampleapi
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
    spec:
      containers:
        - image: pnarang/sampleapi:stable-024cce4e5aa648f770d35e317531bc3b90a633e2
          name: sampleapi
          ports:
            - containerPort: 8000    
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 128Mi